apiVersion: v1
kind: Pod
metadata:
  name: hostpath-pod
spec:
  containers:
  - name: ubuntu
    image: ubuntu:latest
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    command:
    - cat
    tty: true
    volumeMounts:
    - name: hostpath-volume
      mountPath: /root/tmp
  volumes:
  - name: hostpath-volume
    hostPath: 
      path: /run/desktop/mnt/host/c/Users/chosw/temp
