apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuweb-deploy
  annotations:
    kubernetes.io/change-cause: "Deployment Created"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kuweb-label
  template:
    metadata:
      name: kuweb-pod
      labels:
        app: kuweb-label
    spec:
      containers:
        - name: kuweb
          # image: testweb:1.0
          image: testweb:3.0
          resources:
            requests:
              memory: "128Mi"
              cpu: "0.5"
            limits:
              memory: "256Mi"
              cpu: "1"
          ports:
          - containerPort: 8080
            protocol: TCP
