apiVersion: v1
kind: Service
metadata:
  name: mariadb-service
spec:
  type: NodePort
  selector:
    app: mariadb-app
  ports:
  - name: mariadb-port
    port: 3306
    targetPort: 3306
    nodePort: 30028
